services:
  uptime-kuma:
    image: louislam/uptime-kuma:latest
    container_name: uptime-kuma
    restart: unless-stopped

    ports:
      - "3001:3001"

    volumes:
      - lab_uptime_kuma_data:/app/data

volumes:
  lab_uptime_kuma_data:
    name: lab_uptime_kuma_data
