services:
  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    restart: unless-stopped

    ports:
      - "9443:9443"
      - "9000:9000"

    volumes:
      - lab_portainer_data:/data
      - /var/run/docker.sock:/var/run/docker.sock

volumes:
  lab_portainer_data:
    name: lab_portainer_data
